# -*- coding: utf-8 -*-
"""CactusismeBot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10EEUXFA-f4ALbOLX56ihdzIoyRs--pHP
"""

!pip install mwclient
import mwclient
import time

# Connect to Simple Wikipedia
site = mwclient.Site('simple.wikipedia.org')

# Login (replace with your username and bot password)
username = 'CactusismeBot'
password = 'Temporarybotpassword'
site.login(username, password)

def process_vip_reports():
    # Access WP:VIP page
    page = site.pages["Wikipedia:Vandalism in progress"]

    try:
        # Get the text of the page
        vip_text = page.text()

        # Split into sections or lines
        lines = vip_text.split("\n")
        updated_text = []
        for line in lines:
            if "{{done}}" not in line:  # Only process entries not already marked as done
                if "{{vandal|" in line:  # Check for vandal template
                    # Extract the username or IP from the template
                    username_or_ip = extract_vandal_username(line)

                    if username_or_ip and site.users[username_or_ip].get("blockinfo"):
                        # Mark as done
                        line += " {{done}}--~~~~"
            updated_text.append(line)

        # Save changes to WP:VIP
        page.edit("\n".join(updated_text), summary="Marking reports as done.")
    except Exception as e:
        print(f"Error processing WP:VIP: {e}")

def extract_vandal_username(line):
    # Extract the username from the {{vandal|Username}} template
    if "{{vandal|" in line:
        start = line.index("{{vandal|") + len("{{vandal|")
        end = line.index("}}", start)
        return line[start:end].strip()
    return None

# Run the bot periodically
while True:
    process_vip_reports()
    time.sleep(300)  # Run every 5 minutes