name: Archive Choupal
on:
  schedule:
    - cron: '0 3 * * 1'  # Every Monday at 3 AM UTC
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install pywikibot python-dotenv
          
      - name: Login to Wiki (optional - only if bot needs login)
        env:
          WIKI_USERNAME: ${{ secrets.WIKI_USERNAME }}
          WIKI_PASSWORD: ${{ secrets.WIKI_PASSWORD }}
        run: |
          python -c "import pywikibot; pywikibot.Site('hi', 'wikiversity').login()"
          
      - name: Run archiver
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          DRY_RUN: "False"
        run: |
          python scripts/choupal_archiver.py
