name: Run Archive Script

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute
  workflow_dispatch:  # Allows manual trigger

jobs:
      - name: Set Up Pywikibot Credentials
  run: |
    echo "usernames['wikiversity']['hi'] = '${{ secrets.WIKI_USERNAME }}'" > user-config.py
    echo "password_file = 'user-password.py'" >> user-config.py
    echo "('"${{ secrets.WIKI_USERNAME }}"', '"${{ secrets.WIKI_PASSWORD }}"')" > user-password.py

  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install mwparserfromhell pywikibot
          pip install git+https://github.com/Helloeveryone-ctrl/CactusismeBot.git

      - name: Run Script
        run: python cactusismebot.py
