name: Run Archive Script

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install mwparserfromhell pywikibot
          pip install git+https://github.com/Helloeveryone-ctrl/CactusismeBot.git

      - name: Configure Pywikibot Credentials
        run: |
          echo "usernames['wikiversity']['hi'] = '${{ secrets.WIKI_USERNAME }}'" > user-config.py
          echo "password_file = 'user-password.py'" >> user-config.py
          echo "export WIKI_USERNAME='${{ secrets.WIKI_USERNAME }}'" >> $GITHUB_ENV
          echo "export WIKI_PASSWORD='${{ secrets.WIKI_PASSWORD }}'" >> $GITHUB_ENV

      - name: Authenticate Bot
        run: python -m pywikibot login

      - name: Run Script
        env:
          WIKI_USERNAME: ${{ secrets.WIKI_USERNAME }}
          WIKI_PASSWORD: ${{ secrets.WIKI_PASSWORD }}
        run: python cactusismebot.py
